### ISSUE TITLE
As admin, I want to add API tokens without existing users

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#115]
Every API-token now needs a `User` which is completely useless in most cases. API-tokens should be created without an existing `User` present. The following information needs to be present in the new token model.

- organization (optional)
- contactperson (required)
- email (required)
- token
- created
- last_modified

**Tasks**

- [x] Add new API token model, and remove old
- [x] Refactor authorizations to use new model
- [x] Add management command to create token and ask org, contact and email as input (like createsuperuser)
- [x] Adjust admin interface accordingly.

ObjectPermissions can be linked to the API-token but #116 will change this.

**Comment by annashamray** [comment]
@joeribekker 
I have a couple of questions:
* Do you want a management command to have an interactive mode (like `createsuperuser` has)? 
* Is `contact-person` should be a unique field? Or maybe `email`?
