### ISSUE TITLE
As admin, I want to configure Objecttype APIs and Objecttypes by name, and assign permissions per token

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#116]
After #115, permissions can be altered:

`ObjectPermission` is currently modelled as a URL to the Objecttype (API) and a mode which represents the permission. Zero or more `ObjectPermission` are then linked to an `API-token` (or user in the old scenario).

This needs to be refactored to store configured objecttypes once and allow permission to be set on the token (and not on ObjectPermission). Also, the admin should show names instead of UUIDs. To make migrating from one URL (port, domain name) to another, we also need to change how we save the relation to objecttypes.

The new situation should be somewhat like this:

```
class ApiToken(model):
  objecttypes = models.ManyToManyField(through=Permission)
  # + other fields

class Permission(model):
  mode = models.ChoiceField(read/write/etc)
  # + the m2m fields

class Objecttype(model):
  service = models.FK(Service)
  uuid = models.UUIDField
  _name = models.CharField()  # Cached name of the objecttype retrieved from the Objecttype API

  def get_name_display(self):
    return f"{self.service.label}: {self._name}"

class Object(model):
  objecttype_service = models.FK(service)
  objecttype_uuid = models.UUIDField
  # + other fields

  def get_url(self):
    return f"{self.objecttype_service.api_root_url}objecttypes/{self.objecttype_uuid}"
```

**Tasks Object API**

- [x] Add models roughly as the above
- [x] Add admin for `Objecttype` that allows me to choose a configured service (=Objecttype APIs) and choose from a list of objecttypes by name as retrieved from the API. Upon save, also save the `_name`.
- [x] Add the `Permission` model as inline to the `ApiToken` model to configure read/write per objecttype inline.
- [x] Refactor `Object` model to store `objecttype_service` as an FK and the `objecttype_uuid`. The `get_url` method can be used in API responses.
- [x] In the admin, whenever objecttypes are shown, show `get_name_display` and not the `uuid` or `url`.
- [x] Make datamigrations
- [x] If time, optimize the queryset for the get_url function. Maybe a prefetch would do.
