### ISSUE TITLE
Remove jQuery and Bootstrap from vng-api-common so these API's no longer need it

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#300]
For this, we're going to use a fork of VNG-API-Common to not break other API-components.

**Tasks**

* [ ] Remove Boostrap and jQuery from https://github.com/maykinmedia/commonground-api-common
* [ ] Use custom html/css to mimick the basic pages
* [ ] For now, add depenancy on the above Github repo (later we will publish the package)
* [ ] Make sure the home and kanalen page of the API's look as expected
