### ISSUE TITLE
Release patch-versions for OZ/ON/Obj/OT

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/objects-api#436]
### Thema / Theme

Other

### Omschrijving / Description

https://github.com/maykinmedia/open-api-framework/pull/47
https://github.com/maykinmedia/open-api-framework/pull/55
https://github.com/maykinmedia/open-api-framework/pull/49
https://github.com/maykinmedia/open-api-framework/pull/56

And don't forget: https://github.com/maykinmedia/open-api-framework/issues/57

Issue can be split off for each component

**Tasks**
* [ ] Open Zaak https://github.com/open-zaak/open-zaak/pull/1754
* [x] Open Notificaties https://github.com/open-zaak/open-notificaties/pull/182
* [x] Objects API https://github.com/maykinmedia/objects-api/pull/439
* [x] Objecttypes API https://github.com/maykinmedia/objecttypes-api/pull/125
