### ISSUE TITLE
As admin, I want to keep track of meta data with objects

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#72]
As supplied by Constantijn (Utrecht):

> Mijn huiswerk voor de objectenregistratie was om informatie over het G4 metadatamodel te delen.
We kunnen mogelijk een hoop metadatavelden overnemen in de objectenregistratie
> 
> Er is in het verleden met een aantal gemeenten gewerkt aan een gemeenschappelijk metadatamodel voor datasets. De metadatamodellen zijn dus bedoeld voor datasets en niet zozeer voor individuele objecten maar kunnen daarvoor wel bruikbaar zijn.
> 
> De metadatastandaard is ontwikkelt op basis van o.a. de internationale standaard DCAT. DCAT is vertaald naar een Nederlands toepassingsprofiel. Zie https://data.overheid.nl/ondersteuning/open-data/dcat voor meer informatie over DCAT en zie https://dcat-ap-donl.readthedocs.io/en/latest/classes-dataset.html voor het Nederlandse toepassingsprofiel.
> 
> Naast DCAT zijn er ook nog een aantal andere standaarden gebruikt. Ik heb het G4 metadatamodel in de bijlage gezet. Het G4 metadatamodel bestaat uit ongeveer 120 mogelijke velden (niet allemaal verplicht)
> 
> Samen met Rotterdam, Den haag en Leeuwarden is er gewerkt aan een datacatalogus waarin ook metadata is vastgelegd. Het G4 metadatamodel is hier als basis gebruikt maar omdat men het aantal velden te veel vond, is er een verdere selectie gemaakt. De verplichte velden hiervan staan in het bestand verplichte metadatavelden – datacatalogus.
> 
> We kunnen dus gebruik maken van:
> 
> * DCAT
> * G4 metadatamodel
> * Metadatamodel datacatalogus

**Attachments**

[Verplichte metadatavelden - datacatalogus.docx](https://github.com/maykinmedia/objects-api/files/5268978/Verplichte.metadatavelden.-.datacatalogus.docx)
[5B Gezamenlijke aanpak Metadatabeheer (Open) Data in de G4 v0 2 170608.pdf](https://github.com/maykinmedia/objects-api/files/5268979/5B.Gezamenlijke.aanpak.Metadatabeheer.Open.Data.in.de.G4.v0.2.170608.pdf)

**Tasks**

- [x] Read documents
- [x] Choose 1 method (or with reasons, mix them)
- [x] Add relevant fields to API's
- [x] Document reasons why these properties are here and what values can typicall be entered in them.
