### ISSUE TITLE
As productowner, I want to comply to the VNG checklist for standardization

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/objects-api#98]
VNG uses a (work in progress) checklist for promoting an API specification(s) to a VNG standard. We should comply as much as possible to this list.

**Tasks**

- [x] Add checklist to documentation
- [x] Fill in values where compliant or not
- [ ] Wait for final (?) version of VNG
- [ ] Create user stories per checklist item

**Attachments**
[overige registraties - DoD.xlsx](https://github.com/maykinmedia/objects-api/files/5524989/overige.registraties.-.DoD.xlsx)

**Comment by joeribekker** [comment]
It said " partially fixes" @Github ;-)

**Comment by joeribekker** [comment]
The list will probably not be done soon, so move to backlog again.
